import './module'
import './checker/checker'
import './ng-table/ng-table'
import './radio/radio'
import './datepicker/datepicker'
import './ng-echarts/ng-echarts'
import './ng-js-tree/ng-js-tree'
export default 'leadingsoft.ui'
